### ISSUE TITLE
Not working when the protocol is https

### ISSUE THREAD

**Issue by sf-dev-medel** [timw255/SitefinityDetailsViewer#1]
Hi Tim,

The extension doesn't work when the web is using HTTPS.
You have very interesting Sitefinity's projects, good work!!

Cheers,

Edu

**Comment by timw255** [comment]
Given the push for everyone to move to HTTPS, this should definitely be addressed.

**Comment by timw255** [comment]
Added in 1.5.5.

**Comment by anibarro** [comment]
Hi,

Also related with this issue, while using the preview feature in an HTTPS site, the preview seems to be request via HTTP and Chrome blocks the jquery request:

`
jquery-1.9.1.min.js:3 Mixed Content: The page at 'https://domain/Sitefinity/Pages?sf_site=xxx' was loaded over HTTPS, but requested an insecure resource 'http://domain/home'. This request has been blocked; the content must be served over HTTPS.`

Thanks!
